### PR TITLE
front-end-stage

### PR DESCRIPTION
**Pull request by anna-amst**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello Anna! Thanks for sending your code for review! It looks very decent already, but needs some issues corrected. First of all, it's necessary to remove `node_modules` from your repository. Folder `node_modules` shouldn't be included in your project on github because it's too heavy, and can be generated with npm install if necessary.

Please also find some comments below. I believe these issues will be easy for you to fix!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.

* The background image in the header doesn't match figma, it should be not that bright, white text is not comfortable to read now. Please export the image from figma.
* In logged-in state, cards should have bookmark icons to add a card to saved on home page, not the transh bin icon: https://prnt.sc/O2fgYQjkoWyN
* Please add possibility to save cards or some hard-coded sample cards to saved-news pages so that I can check the layout.
* When search is being performed, only preloader should be displayed, title "Search results" should be displayed only after a successful search

- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* On mobile screens, popups are not possible to close, because the closing button is not displayed.
* https://prnt.sc/ntPl_kHNC-_P Mobile layout of saved-news doesn't match the design. Note that the button to open navigation isn't seen

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Links in footer should be working links, opening in new tabs.
* NotFound component hasn't been built in the application logic. It should be displayed instead of Search results in case nothing is found.

- [ ]  Classes are named according to BEM specifications.

* `navigation__home__active` Elements of elements are forbidden, only blocks can have elements.
* https://prnt.sc/6R8T5lHZHcs5 Elements can't be used without their block. There are many similar cases in the project, please correct all of them

- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* Links in `header` and `footer` should be in nav, ul or ul inside nav.
* There should be only one h1 per page.
* news cards list should be a list `<ul>`, or/and the card needs to be `<article>`
* The page html structure has some excessive div wrappers https://prnt.sc/CVO7_cqS-QnH .
* "Search results", "About" should be `<section>`
* `br` between paragraphs should be removed ("about" section)

- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [ ]  The popup windows have opening and closing functionality implemented.

* On mobile screens, popups are not possible to close, because the closing button is not displayed.

- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* "Search" and "Show more" buttons are missing hover and active effecs from figma

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 42

**Comment by anna-amst** [comment]
Hi, so I added this div with the className "page__background" to both components so the background image covers the header and the main section. I don't know how to do it otherwise, could you give me a direction if it's not a good practice. Appreciate it.

(The page html structure has some excessive div wrappers https://prnt.sc/CVO7_cqS-QnH .)

**Comment by ImaliaNsk** [comment]
Hello! Thank you for the fixes, the project looks almost perfect. Please see the list below and make the final corrections:

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* Main page scrolls horizontally on 320 - 391, 689 - 706
* Saved-new has a scroll on 689 - 786

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* NotFound icon doesn't match the design: https://prnt.sc/4uZqm7ioIGRs

- [x]  Classes are named according to BEM specifications.
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* There should be only one h1 per page.
* The page html structure has some excessive div wrappers https://prnt.sc/UMyGIbpV1Lgx You could add class with a background to header and main elements, without wrapping them each into a div.

- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* "Search" button is missing "active" effect from figma

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.

* https://prnt.sc/JraG89Pww95D Please correct all similar cases

- [ ]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 76

**Comment by ImaliaNsk** [comment]
Congratulations, the project is accepted! Good luck on the next stage! 

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* https://prnt.sc/B4M9LBf43osb https://prnt.sc/Ifi_uJNvJSJ9 These white margins should be removed

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Not loaded image: https://prnt.sc/t26IFxY4nLcP

- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Images have an `alt` attribute containing appropriate values.

* Icons in footer

- [ ]  Raster and vector images have been optimized.

## Number of points: 84

**Pull request merged**
